# Generated by Django 3.2.3 on 2021-05-30 02:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permission_data',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='permission_on',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
