# Generated by Django 3.2.3 on 2021-05-30 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='id',
        ),
        migrations.RemoveField(
            model_name='facilitykh',
            name='id',
        ),
        migrations.AddField(
            model_name='facility',
            name='facility',
            field=models.CharField(default=' ', editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facilitykh',
            name='facility',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
