# Generated by Django 3.2.3 on 2021-05-30 01:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('check_date', models.DateTimeField(auto_now=True)),
                ('trainee', models.TextField()),
                ('course', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('certification_type', models.CharField(max_length=255)),
                ('detail', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('trainee', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('course_type', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_certification', models.BooleanField(default=True)),
                ('certification', models.TextField()),
                ('partner_involved', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('name_kh', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=255)),
                ('province', models.TextField()),
                ('operating_district', models.TextField()),
                ('facility', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
