# Generated by Django 3.2.3 on 2021-05-30 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_auto_20210530_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='facility',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='operating_district',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='province',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='facility',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='operating_district',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='province',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
